SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM audit_logs;
DELETE FROM bank_accounts;
DELETE FROM bank_deposits;
DELETE FROM bank_reconciliations;
DELETE FROM brick_production_projects;
DELETE FROM brick_production_records;
DELETE FROM brick_transfers;
DELETE FROM cash_accounts;
DELETE FROM cheques;
DELETE FROM coop_members;
DELETE FROM customer_activities;
DELETE FROM deposit_items;
DELETE FROM expenses;
DELETE FROM expense_attachments;
DELETE FROM inventory_balances;
DELETE FROM invoice_items;
DELETE FROM invoices;
DELETE FROM journal_lines;
DELETE FROM journal_entries;
DELETE FROM ledger_entries;
DELETE FROM machinery;
DELETE FROM machinery_rentals;
DELETE FROM member_fixed_deposits;
DELETE FROM parties;
DELETE FROM party_opening_balances;
DELETE FROM payment_receipts;
DELETE FROM plantation_harvest_transfers;
DELETE FROM plantation_harvests;
DELETE FROM plantation_project_crops;
DELETE FROM plantation_projects;
DELETE FROM products;
DELETE FROM product_categories;
DELETE FROM services;
DELETE FROM service_jobs;
DELETE FROM stock_ledger;

ALTER TABLE audit_logs AUTO_INCREMENT = 1;
ALTER TABLE bank_accounts AUTO_INCREMENT = 1;
ALTER TABLE bank_deposits AUTO_INCREMENT = 1;
ALTER TABLE bank_reconciliations AUTO_INCREMENT = 1;
ALTER TABLE brick_production_projects AUTO_INCREMENT = 1;
ALTER TABLE brick_production_records AUTO_INCREMENT = 1;
ALTER TABLE brick_transfers AUTO_INCREMENT = 1;
ALTER TABLE cash_accounts AUTO_INCREMENT = 1;
ALTER TABLE cheques AUTO_INCREMENT = 1;
ALTER TABLE coop_members AUTO_INCREMENT = 1;
ALTER TABLE customer_activities AUTO_INCREMENT = 1;
ALTER TABLE deposit_items AUTO_INCREMENT = 1;
ALTER TABLE expenses AUTO_INCREMENT = 1;
ALTER TABLE expense_attachments AUTO_INCREMENT = 1;
ALTER TABLE inventory_balances AUTO_INCREMENT = 1;
ALTER TABLE invoice_items AUTO_INCREMENT = 1;
ALTER TABLE invoices AUTO_INCREMENT = 1;
ALTER TABLE journal_lines AUTO_INCREMENT = 1;
ALTER TABLE journal_entries AUTO_INCREMENT = 1;
ALTER TABLE ledger_entries AUTO_INCREMENT = 1;
ALTER TABLE machinery AUTO_INCREMENT = 1;
ALTER TABLE machinery_rentals AUTO_INCREMENT = 1;
ALTER TABLE member_fixed_deposits AUTO_INCREMENT = 1;
ALTER TABLE parties AUTO_INCREMENT = 1;
ALTER TABLE party_opening_balances AUTO_INCREMENT = 1;
ALTER TABLE payment_receipts AUTO_INCREMENT = 1;
ALTER TABLE plantation_harvest_transfers AUTO_INCREMENT = 1;
ALTER TABLE plantation_harvests AUTO_INCREMENT = 1;
ALTER TABLE plantation_project_crops AUTO_INCREMENT = 1;
ALTER TABLE plantation_projects AUTO_INCREMENT = 1;
ALTER TABLE products AUTO_INCREMENT = 1;
ALTER TABLE product_categories AUTO_INCREMENT = 1;
ALTER TABLE services AUTO_INCREMENT = 1;
ALTER TABLE service_jobs AUTO_INCREMENT = 1;
ALTER TABLE stock_ledger AUTO_INCREMENT = 1;

SET FOREIGN_KEY_CHECKS = 1;