SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE audit_logs;
TRUNCATE TABLE bank_accounts;
TRUNCATE TABLE bank_deposits;
TRUNCATE TABLE bank_reconciliations;
TRUNCATE TABLE brick_production_projects;
TRUNCATE TABLE brick_production_records;
TRUNCATE TABLE brick_transfers;
TRUNCATE TABLE cash_accounts;
TRUNCATE TABLE cheques;
TRUNCATE TABLE coop_members;
TRUNCATE TABLE customer_activities;
TRUNCATE TABLE deposit_items;
TRUNCATE TABLE expenses;
TRUNCATE TABLE expense_attachments;
TRUNCATE TABLE inventory_balances;
TRUNCATE TABLE invoice_items;
TRUNCATE TABLE invoices;
TRUNCATE TABLE journal_lines;
TRUNCATE TABLE journal_entries;
TRUNCATE TABLE ledger_entries;
TRUNCATE TABLE machinery;
TRUNCATE TABLE machinery_rentals;
TRUNCATE TABLE member_fixed_deposits;
TRUNCATE TABLE parties;
TRUNCATE TABLE party_opening_balances;
TRUNCATE TABLE payment_receipts;
TRUNCATE TABLE plantation_harvest_transfers;
TRUNCATE TABLE plantation_harvests;
TRUNCATE TABLE plantation_project_crops;
TRUNCATE TABLE plantation_projects;
TRUNCATE TABLE products;
TRUNCATE TABLE product_categories;
TRUNCATE TABLE services;
TRUNCATE TABLE service_jobs;
TRUNCATE TABLE stock_ledger;

SET FOREIGN_KEY_CHECKS = 1;